.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-src-clean 1  "maw-src-clean " 
.SH NAME
maw\-src\-clean \- free the build cache: old builds nothing needs and dependencies no build uses
.SH SYNOPSIS
\fBmaw src clean\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
free the build cache: old builds nothing needs and dependencies no build uses
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
print help
.SH EXTRA
see: maw help source packages
