.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-enable 1  "maw-sv-enable " 
.SH NAME
maw\-sv\-enable \- record a service in maw.nix and link it into place
.SH SYNOPSIS
\fBmaw sv enable\fR [\fB\-\-user\fR] [\fB\-\-system\fR] [\fB\-\-here\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
record a service in maw.nix and link it into place
.SH OPTIONS
.TP
\fB\-\-user\fR
the user service run by your session
.TP
\fB\-\-system\fR
the system service run from boot
.TP
\fB\-\-here\fR
record it for this machine only
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

