.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-src-update 1  "maw-src-update " 
.SH NAME
maw\-src\-update \- move a template to its upstream\*(Aqs current version or newest release, then rebuild
.SH SYNOPSIS
\fBmaw src update\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
move a template to its upstream\*(Aqs current version or newest release, then rebuild
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

