.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-generations 1  "maw-generations " 
.SH NAME
maw\-generations \- list generations: each activation that changed something
.SH SYNOPSIS
\fBmaw generations\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
list generations: each activation that changed something
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
see: maw help generations
