.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-list 1  "maw-sv-list " 
.SH NAME
maw\-sv\-list \- declared and enabled services, and whether they run
.SH SYNOPSIS
\fBmaw sv list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
declared and enabled services, and whether they run
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
