.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-adopt 1  "maw-adopt " 
.SH NAME
maw\-adopt \- record installed packages and enabled services maw.nix doesn\*(Aqt know about
.SH SYNOPSIS
\fBmaw adopt\fR [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
record installed packages and enabled services maw.nix doesn\*(Aqt know about
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR
print the checklist without opening it
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
see: maw help adopting
