.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-log 1  "maw-sv-log " 
.SH NAME
maw\-sv\-log \- follow a service\*(Aqs log
.SH SYNOPSIS
\fBmaw sv log\fR [\fB\-\-user\fR] [\fB\-\-system\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
follow a service\*(Aqs log
.SH OPTIONS
.TP
\fB\-\-user\fR
the user service run by your session
.TP
\fB\-\-system\fR
the system service run from boot
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

