.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-status 1  "maw-status " 
.SH NAME
maw\-status \- everything out of sync: files, packages, services, and config for missing programs
.SH SYNOPSIS
\fBmaw status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
everything out of sync: files, packages, services, and config for missing programs
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
see: maw help checking
