.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-build 1  "maw-build " 
.SH NAME
maw\-build \- render changed modules into out/
.SH SYNOPSIS
\fBmaw build\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
render changed modules into out/
.SH OPTIONS
.TP
\fB\-\-force\fR
overwrite out/ files edited in place, backing them up
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
see: maw help building
