.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-wallpaper 1  "maw-wallpaper " 
.SH NAME
maw\-wallpaper \- set the wallpaper the theme comes from, or show it
.SH SYNOPSIS
\fBmaw wallpaper\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIMAGE\fR] 
.SH DESCRIPTION
set the wallpaper the theme comes from, or show it
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIMAGE\fR]
an image (copied into static/wallpapers/), a name already there, or random
.SH EXTRA
see: maw help wallpaper themes
