.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-host 1  "maw-host " 
.SH NAME
maw\-host \- show or set this machine\*(Aqs name, which picks its hosts/<name>.nix and own packages
.SH SYNOPSIS
\fBmaw host\fR [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
show or set this machine\*(Aqs name, which picks its hosts/<name>.nix and own packages
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR]
a new name for this machine
.SH EXTRA
see: maw help more than one machine
