.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-restart 1  "maw-sv-restart " 
.SH NAME
maw\-sv\-restart \- sv restart
.SH SYNOPSIS
\fBmaw sv restart\fR [\fB\-\-user\fR] [\fB\-\-system\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
sv restart
.SH OPTIONS
.TP
\fB\-\-user\fR
the user service run by your session
.TP
\fB\-\-system\fR
the system service run from boot
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

