.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-commit 1  "maw-commit " 
.SH NAME
maw\-commit \- commit every change in the repo
.SH SYNOPSIS
\fBmaw commit\fR [\fB\-m\fR|\fB\-\-message\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
commit every change in the repo
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-message\fR \fI<MESSAGE>\fR
the message; without it git opens your editor
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
see: maw help generations
