.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-query 1  "maw-query " 
.SH NAME
maw\-query \- list packages you installed, or show one
.SH SYNOPSIS
\fBmaw query\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGE\fR] 
.SH DESCRIPTION
list packages you installed, or show one
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACKAGE\fR]

.SH EXTRA
see: maw help looking things up
