.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-secret-edit 1  "maw-secret-edit " 
.SH NAME
maw\-secret\-edit \- decrypt a file into your editor, then encrypt it back and activate
.SH SYNOPSIS
\fBmaw secret edit\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
decrypt a file into your editor, then encrypt it back and activate
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
the live file, or its static/<name>/<file>.age
