.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-secret 1  "maw-secret " 
.SH NAME
maw\-secret \- encrypted files in static/: edit one, or re\-encrypt all for every machine
.SH SYNOPSIS
\fBmaw secret\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
encrypted files in static/: edit one, or re\-encrypt all for every machine
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
maw\-secret\-edit(1)
decrypt a file into your editor, then encrypt it back and activate
.TP
maw\-secret\-rekey(1)
re\-encrypt every file for every machine in hosts/*.pub, after adding one
.SH EXTRA
see: maw help encrypted files
