.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-secret-rekey 1  "maw-secret-rekey " 
.SH NAME
maw\-secret\-rekey \- re\-encrypt every file for every machine in hosts/*.pub, after adding one
.SH SYNOPSIS
\fBmaw secret rekey\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
re\-encrypt every file for every machine in hosts/*.pub, after adding one
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
