.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-disable 1  "maw-sv-disable " 
.SH NAME
maw\-sv\-disable \- stop and unlink a service, and drop it from maw.nix
.SH SYNOPSIS
\fBmaw sv disable\fR [\fB\-\-user\fR] [\fB\-\-system\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
stop and unlink a service, and drop it from maw.nix
.SH OPTIONS
.TP
\fB\-\-user\fR
the user service run by your session
.TP
\fB\-\-system\fR
the system service run from boot
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

