.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-info 1  "maw-info " 
.SH NAME
maw\-info \- a package\*(Aqs details, and whether maw manages it
.SH SYNOPSIS
\fBmaw info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
a package\*(Aqs details, and whether maw manages it
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>

.SH EXTRA
see: maw help looking things up
