.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-doctor 1  "maw-doctor " 
.SH NAME
maw\-doctor \- check the session for problems that break a desktop quietly, like a missing session bus
.SH SYNOPSIS
\fBmaw doctor\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
check the session for problems that break a desktop quietly, like a missing session bus
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
print help
.SH EXTRA
see: maw help doctor
