.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-sv-status 1  "maw-sv-status " 
.SH NAME
maw\-sv\-status \- show a service\*(Aqs state
.SH SYNOPSIS
\fBmaw sv status\fR [\fB\-\-user\fR] [\fB\-\-system\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
show a service\*(Aqs state
.SH OPTIONS
.TP
\fB\-\-user\fR
the user service run by your session
.TP
\fB\-\-system\fR
the system service run from boot
.TP
\fB\-h\fR, \fB\-\-help\fR
print help
.TP
<\fINAME\fR>
a service, by its name in /etc/sv or ~/.config/sv
.SH EXTRA
see: maw help service commands
