.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-search 1  "maw-search " 
.SH NAME
maw\-search \- search every package source, then the aur and nixpkgs when none has it
.SH SYNOPSIS
\fBmaw search\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITERM\fR> 
.SH DESCRIPTION
search every package source, then the aur and nixpkgs when none has it
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITERM\fR>
a term, or <source>:<term> to search one: xbps, flatpak, cargo, uv, npm, aur, nixpkgs
.SH EXTRA
see: maw help looking things up
