.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maw-src-build 1  "maw-src-build " 
.SH NAME
maw\-src\-build \- build a template with xbps\-src; an installed package is upgraded to the new build
.SH SYNOPSIS
\fBmaw src build\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
build a template with xbps\-src; an installed package is upgraded to the new build
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

